name: Terraform Checks

on:
  workflow_dispatch:
  pull_request:
  push:
    paths:
      - '**.tf'

permissions:
  contents: read

jobs:
  validate-and-format:
    name: Validate and Format Terraform Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Setup Terraform
        id: terraform
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
      
      - name: Initialize Terraform
        id: init
        run: terraform init -backend=false

      - name: Validate Terraform
        id: validate
        run: terraform validate

      - name: Format Terraform
        id: format
        run: terraform fmt -check -recursive
